import { createContext, useContext } from 'react';

/* ── Types ───────────────────────────────────── */
export type ToastVariant = 'default' | 'success' | 'error' | 'accent';

/**
 * Internal data shape for a single toast notification, including its unique `id` assigned
 * by the provider. Consumers should use {@link ToastInput} when calling `toast()`.
 */
export interface ToastData {
  id: string;
  title: string;
  description?: string;
  variant?: ToastVariant;
  /** Auto-dismiss in ms. 0 = manual dismiss only. */
  duration?: number;
}

/**
 * Input type passed to the `toast()` function from `useToast()`. Identical to
 * {@link ToastData} but without the `id` field, which is auto-generated by the provider.
 *
 * @example
 * const { toast } = useToast();
 * toast({ title: "Saved", variant: "success" });
 */
export type ToastInput = Omit<ToastData, 'id'>;

/**
 * Value provided by the Toast context. Consumed via the `useToast()` hook.
 *
 * - `toast()` — creates and displays a new transient notification.
 * - `dismiss()` — programmatically removes a toast by its `id`.
 */
export interface ToastContextValue {
  toast: (data: ToastInput) => void;
  dismiss: (id: string) => void;
}

/* ── Context + Hook ──────────────────────────── */
export const ToastContext = createContext<ToastContextValue | null>(null);

export function useToast(): ToastContextValue {
  const ctx = useContext(ToastContext);
  if (!ctx) throw new Error('useToast must be used within <ToastProvider>');
  return ctx;
}
