import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("node:child_process", () => ({
  execFile: vi.fn(),
}));

vi.mock("node:util", () => ({
  promisify: vi.fn((fn: unknown) => fn),
}));

import { execFile } from "node:child_process";
import {
  isPrAiAuthor,
  extractPrNumberFromMessage,
  formatRevertForIssue,
  detectRecentReverts,
  getCommitDetails,
} from "../revert-detector.js";

const mockExecFile = vi.mocked(
  execFile as unknown as (...args: unknown[]) => Promise<{ stdout: string }>
);

describe("revert-detector", () => {
  describe("isPrAiAuthor", () => {
    it("detects AI-authored PR marker", () => {
      const prBody = `## Summary

Agent-generated PR for task:

> Fix a bug

## Agent Metadata

Generated by @mbe/agent-core`;

      expect(isPrAiAuthor(prBody)).toBe(true);
    });

    it("returns false for non-AI-authored PRs", () => {
      const prBody = `## Summary

Manual fix for a bug`;

      expect(isPrAiAuthor(prBody)).toBe(false);
    });

    it("works with partial matches", () => {
      const prBody = "This was Generated by @mbe/agent-core for testing";
      expect(isPrAiAuthor(prBody)).toBe(true);
    });
  });

  describe("extractPrNumberFromMessage", () => {
    it("extracts PR number from message", () => {
      const message = 'Revert "feat: Add feature (#1234)"';
      const prNumber = extractPrNumberFromMessage(message);
      expect(prNumber).toBe(1234);
    });

    it("extracts first PR number when multiple present", () => {
      const message = "Revert commit #1234 (originally from #5678)";
      const prNumber = extractPrNumberFromMessage(message);
      expect(prNumber).toBe(1234);
    });

    it("returns undefined when no PR number found", () => {
      const message = "Revert commit abc123def";
      const prNumber = extractPrNumberFromMessage(message);
      expect(prNumber).toBeUndefined();
    });

    it("handles large PR numbers", () => {
      const message = "Revert #99999 for emergency fix";
      const prNumber = extractPrNumberFromMessage(message);
      expect(prNumber).toBe(99999);
    });
  });

  describe("formatRevertForIssue", () => {
    it("formats revert commit for issue table", () => {
      const revert = {
        sha: "abc123def456789",
        oneline: 'Revert "feat: Add feature (#1234)"',
        message: "Revert commit\n\nThis reverts commit abc123def",
        revertedPrNumber: 1234,
        timestamp: "2026-05-10T14:30:00Z",
      };

      const formatted = formatRevertForIssue(revert, true);

      expect(formatted).toContain("abc123d");
      expect(formatted).toContain('Revert "feat');
      expect(formatted).toContain("#1234");
      expect(formatted).toContain("🤖 AI-authored");
      expect(formatted).toContain("2026-05-10");
    });

    it("shows manual author when not AI-authored", () => {
      const revert = {
        sha: "def456abc123",
        oneline: 'Revert "test: Remove test"',
        message: "Manual revert",
        timestamp: "2026-05-10T14:30:00Z",
      };

      const formatted = formatRevertForIssue(revert, false);

      expect(formatted).toContain("👤 Manual");
      expect(formatted).not.toContain("🤖");
    });

    it("shows unknown when no PR number", () => {
      const revert = {
        sha: "ghi789jkl012",
        oneline: "Revert broken commit",
        message: "Manual revert",
        timestamp: "2026-05-10T14:30:00Z",
      };

      const formatted = formatRevertForIssue(revert, false);

      expect(formatted).toContain("unknown");
    });
  });
});

// ── git subprocess timeout ──────────────────────────────────────────────────

describe("git subprocess timeout", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("passes a numeric timeout on every git call in detectRecentReverts", async () => {
    mockExecFile.mockImplementation(async (...args: unknown[]) => {
      const argList = args[1] as string[];
      if (argList[0] === "log") {
        return { stdout: 'abc1234 Revert "feat: thing (#42)"' };
      }
      return { stdout: "Revert commit\n\nThis reverts commit abc1234" };
    });

    await detectRecentReverts("/repo");

    expect(mockExecFile.mock.calls.length).toBeGreaterThan(0);
    for (const call of mockExecFile.mock.calls) {
      const options = call[2] as { timeout?: number } | undefined;
      expect(typeof options?.timeout).toBe("number");
      expect(options?.timeout).toBeGreaterThan(0);
    }
  });

  it("passes a numeric timeout on every git call in getCommitDetails", async () => {
    mockExecFile.mockResolvedValue({ stdout: "some output" });

    await getCommitDetails("/repo", "abc1234");

    expect(mockExecFile.mock.calls.length).toBeGreaterThan(0);
    for (const call of mockExecFile.mock.calls) {
      const options = call[2] as { timeout?: number } | undefined;
      expect(typeof options?.timeout).toBe("number");
      expect(options?.timeout).toBeGreaterThan(0);
    }
  });
});
