blank_issues_enabled: false
contact_links:
  - name: Questions or discussion
    url: https://github.com/mattbutlerengineering/mattbutlerengineering/discussions
    about: Use discussions for questions, ideas, or general conversation
