import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { z } from "zod";
import type { PrOptions, PrResult } from "./types.js";

const execFileAsync = promisify(execFile);

const GhPrResultSchema = z.object({
  url: z.string().url(),
  number: z.number().int(),
});

export async function createPullRequest(options: PrOptions): Promise<PrResult> {
  const { title, body, baseBranch, branchName, repoPath } = options;

  const { stdout } = await execFileAsync(
    "gh",
    [
      "pr",
      "create",
      "--title",
      title,
      "--body",
      body,
      "--base",
      baseBranch,
      "--head",
      branchName,
      "--json",
      "url,number",
    ],
    { cwd: repoPath }
  );

  const parsed = GhPrResultSchema.parse(JSON.parse(stdout.trim()));
  return { url: parsed.url, number: parsed.number };
}

export function buildPrTitle(taskDescription: string): string {
  const prefix = "feat";
  const description = taskDescription.length > 60
    ? taskDescription.slice(0, 57) + "..."
    : taskDescription;
  return `${prefix}: ${description}`;
}

export function buildPrBody(
  taskDescription: string,
  sessionId: string,
  costUsd: number,
  numTurns: number
): string {
  return [
    "## Summary",
    "",
    `Agent-generated PR for task:`,
    "",
    `> ${taskDescription}`,
    "",
    "## Agent Metadata",
    "",
    `| Field | Value |`,
    `|-------|-------|`,
    `| Session ID | \`${sessionId}\` |`,
    `| Cost | $${costUsd.toFixed(4)} |`,
    `| Turns | ${numTurns} |`,
    "",
    "## Test Plan",
    "",
    "- [ ] Review generated changes",
    "- [ ] Run CI pipeline",
    "- [ ] Verify no security issues",
    "",
    "---",
    "*Generated by @mbe/agent-core*",
  ].join("\n");
}
