import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { z } from "zod";
import type { PrOptions, PrResult } from "./types.js";

const execFileAsync = promisify(execFile);

const GhPrResultSchema = z.object({
  url: z.url(),
  number: z.number().int(),
});

export async function createPullRequest(options: PrOptions): Promise<PrResult> {
  const { title, body, baseBranch, branchName, repoPath, draft } = options;

  const args = [
    "pr",
    "create",
    "--title",
    title,
    "--body",
    body,
    "--base",
    baseBranch,
    "--head",
    branchName,
    "--json",
    "url,number",
  ];

  if (draft) {
    args.push("--draft");
  }

  const { stdout } = await execFileAsync("gh", args, { cwd: repoPath });

  const parsed = GhPrResultSchema.parse(JSON.parse(stdout.trim()));
  return { url: parsed.url, number: parsed.number };
}

export function buildPrTitle(taskDescription: string): string {
  const prefix = "feat";
  const description = taskDescription.length > 60
    ? taskDescription.slice(0, 57) + "..."
    : taskDescription;
  return `${prefix}: ${description}`;
}

export function buildPrBody(
  taskDescription: string,
  sessionId: string,
  costUsd: number,
  numTurns: number
): string {
  return [
    "## Summary",
    "",
    `Agent-generated PR for task:`,
    "",
    `> ${taskDescription}`,
    "",
    "## Agent Metadata",
    "",
    `| Field | Value |`,
    `|-------|-------|`,
    `| Session ID | \`${sessionId}\` |`,
    `| Cost | $${costUsd.toFixed(4)} |`,
    `| Turns | ${numTurns} |`,
    "",
    "## Test Plan",
    "",
    "- [ ] Review generated changes",
    "- [ ] Run CI pipeline",
    "- [ ] Verify no security issues",
    "",
    "---",
    "*Generated by @mbe/agent-core*",
  ].join("\n");
}

export function buildFailurePrBody(
  taskDescription: string,
  errors: readonly string[],
  stuckPattern?: string
): string {
  const lines = [
    "## Summary",
    "",
    "**This is a draft PR from a failed agent session.** The agent made partial progress but did not complete the task. Human review is needed.",
    "",
    `> ${taskDescription}`,
    "",
    "## Failure Details",
    "",
  ];

  if (stuckPattern) {
    lines.push(`**Stuck pattern:** \`${stuckPattern}\``);
    lines.push("");
  }

  if (errors.length > 0) {
    lines.push("**Errors:**");
    for (const err of errors) {
      lines.push(`- ${err}`);
    }
    lines.push("");
  }

  lines.push(
    "## Next Steps",
    "",
    "- [ ] Review partial changes for useful work",
    "- [ ] Determine if a different approach is needed",
    "- [ ] Close this PR if changes are not salvageable",
    "",
    "---",
    "*Generated by @mbe/agent-core (failed session)*"
  );

  return lines.join("\n");
}
