import { execFile } from "node:child_process";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

export interface RevertCommit {
  sha: string;
  oneline: string;
  message: string;
  revertedSha?: string;
  revertedPrNumber?: number;
  timestamp: string;
}

export interface RevertedPR {
  number: number;
  title: string;
  url: string;
  isAiAuthor: boolean;
  revertedAt: string;
}

/**
 * Detects revert commits in the last 24 hours on main branch.
 */
export async function detectRecentReverts(
  repoPath: string,
  hoursBack: number = 24
): Promise<RevertCommit[]> {
  try {
    const { stdout } = await execFileAsync("git", ["log", `--since=${hoursBack} hours ago`, "--oneline", "--grep=^Revert", "main"], {
      cwd: repoPath,
    });

    const commits = stdout
      .trim()
      .split("\n")
      .filter((line) => line.trim())
      .map((line) => {
        const [sha, ...rest] = line.split(" ");
        const oneline = rest.join(" ");
        return { sha, oneline };
      });

    const detailed: RevertCommit[] = [];
    for (const commit of commits) {
      const { stdout: message } = await execFileAsync("git", ["show", "-s", "--format=%B", commit.sha], {
        cwd: repoPath,
      });

      // Extract reverted PR number from message
      const prMatch = message.match(/#(\d+)/);
      const prNumber = prMatch ? parseInt(prMatch[1], 10) : undefined;

      // Extract reverted commit SHA
      const revertedMatch = message.match(/This reverts commit (\w+)/);
      const revertedSha = revertedMatch?.[1];

      // Get timestamp
      const { stdout: timestampStr } = await execFileAsync(
        "git",
        ["show", "-s", "--format=%aI", commit.sha],
        { cwd: repoPath }
      );

      detailed.push({
        sha: commit.sha,
        oneline: commit.oneline,
        message: message.trim(),
        revertedSha,
        revertedPrNumber: prNumber,
        timestamp: timestampStr.trim(),
      });
    }

    return detailed;
  } catch {
    // No reverts found or git error
    return [];
  }
}

/**
 * Checks if a PR body contains the AI-author marker.
 */
export function isPrAiAuthor(prBody: string): boolean {
  return prBody.includes("Generated by @mbe/agent-core");
}

/**
 * Extracts PR number from a git commit message.
 */
export function extractPrNumberFromMessage(message: string): number | undefined {
  const match = message.match(/#(\d+)/);
  return match ? parseInt(match[1], 10) : undefined;
}

/**
 * Gets git log for a specific commit.
 */
export async function getCommitDetails(
  repoPath: string,
  sha: string
): Promise<{ message: string; timestamp: string } | null> {
  try {
    const { stdout: message } = await execFileAsync("git", ["show", "-s", "--format=%B", sha], {
      cwd: repoPath,
    });
    const { stdout: timestamp } = await execFileAsync("git", ["show", "-s", "--format=%aI", sha], {
      cwd: repoPath,
    });
    return {
      message: message.trim(),
      timestamp: timestamp.trim(),
    };
  } catch {
    // Commit not found or git error
    return null;
  }
}

/**
 * Formats a revert commit for human-readable output.
 */
export function formatRevertForIssue(revert: RevertCommit, isAiAuthor: boolean): string {
  const prInfo = revert.revertedPrNumber ? `PR #${revert.revertedPrNumber}` : revert.revertedSha || "unknown";
  const authorMark = isAiAuthor ? "🤖 AI-authored" : "👤 Manual";

  return `| ${revert.sha.slice(0, 7)} | ${revert.oneline} | ${prInfo} | ${authorMark} | ${new Date(revert.timestamp).toISOString().split("T")[0]} |`;
}

/**
 * Detects AI-authored PR reverts from the last N hours.
 */
export async function detectAiAuthorReverts(
  repoPath: string,
  hoursBack: number = 24
): Promise<{ commit: RevertCommit; prNumber: number }[]> {
  const reverts = await detectRecentReverts(repoPath, hoursBack);
  const results: { commit: RevertCommit; prNumber: number }[] = [];

  for (const revert of reverts) {
    if (revert.revertedPrNumber) {
      // Note: In a real implementation, we'd query GitHub to check if PR is AI-authored
      // For now, we'll return all reverts and let the caller check
      results.push({
        commit: revert,
        prNumber: revert.revertedPrNumber,
      });
    }
  }

  return results;
}
