import { randomUUID } from "node:crypto";
import { expect } from "vitest";
import Stripe from "stripe";
import {
  ADMIN_HEADERS,
  asAdmin,
  expectBroken,
  expectDenied,
  expectOk,
  type ExpectBrokenOptions,
  type PayloadOrFactory,
  type RouteFixture,
  type SweepContext,
} from "./rls-route-sweep.fixtures.js";

/**
 * #5369 PR 2 (broken) / PR 8 (fixed) — the public-funnel, token-route, and
 * Stripe-webhook half of the route sweep. Split out of
 * `rls-route-sweep.fixtures.ts` (which had grown past this repo's 800-line
 * file guideline) rather than folded into it — these routes share one
 * property the staff API doesn't: every one of them is ADR-026 §3.3 item 3 or
 * item 4, so every fixture here (except `holdConfirmFixtures`, below) is now
 * "ok": item 3 (`resolveVenueId("venue_slug", …)` + `runWithVenueContext`,
 * replacing an unscoped `venueService.getBySlug`/`getPublicConfigBySlug`
 * read) covers the entire `/public/v1/venues/:slug/*` funnel, and item 4
 * (token-addressed guest surfaces, plus the Stripe webhook's
 * `depositService.getByPaymentIntentId`) covers the manage/confirm/
 * unsubscribe routes and the webhook. One admin-shaped request proves the
 * success leg and one wrong-venue/unknown-slug/gone-token request proves the
 * denial leg for each: none of these routes have a `requireVenueAccess`
 * guard at all (they authenticate via slug, a capability token, or a webhook
 * signature, never a JWT + membership check), so there is no "member" leg to
 * run either.
 */

async function loadTokenHelpers(): Promise<{
  generateManageToken: (reservationId: string, guestEmail: string) => string;
  generateUnsubscribeToken: (guestId: string) => string;
}> {
  const [{ generateManageToken }, { generateUnsubscribeToken }] = await Promise.all([
    import("./public-reservations.js"),
    import("../services/post-visit-notifier.js"),
  ]);
  return { generateManageToken, generateUnsubscribeToken };
}

/** A headers value, or a factory reading it off {@link SweepContext} (e.g. the seeded `holdSessionId`). */
type HeadersOrFactory = Record<string, string> | ((ctx: SweepContext) => Record<string, string>);

/** Still used by `holdConfirmFixtures` below — the one fixture in this file that stays genuinely broken. */
function brokenPublic(
  blocker: string,
  method: "GET" | "POST" | "PATCH" | "DELETE",
  urlFor: (ctx: SweepContext) => string,
  payloadFor?: PayloadOrFactory,
  options: { headersFor?: HeadersOrFactory; expectBrokenOptions?: ExpectBrokenOptions } = {}
): RouteFixture {
  return {
    kind: "broken",
    blocker,
    run: async (ctx) => {
      const url = urlFor(ctx);
      const payload = typeof payloadFor === "function" ? payloadFor(ctx) : payloadFor;
      const headers =
        typeof options.headersFor === "function" ? options.headersFor(ctx) : options.headersFor;
      expectBroken(
        await asAdmin(ctx, { method, url, payload, ...(headers ? { headers } : {}) }),
        `${method} ${url}`,
        ctx,
        options.expectBrokenOptions
      );
    },
  };
}

/** An unknown slug — proves item 3's denial leg without depending on any seeded venue. */
const UNKNOWN_SLUG = "rls-sweep-no-such-slug";

/**
 * Creates a disposable hold via the already-proven public create-hold route
 * (`POST /public/v1/venues/:slug/holds`, `publicFunnelFixtures` below). Used
 * by every public-funnel fixture that needs a REAL hold to confirm/read —
 * never `ctx.holdA`, which `holdConfirmFixtures`'s still-broken,
 * out-of-scope `POST /api/v1/holds/:id/confirm` fixture also depends on.
 */
async function createDisposablePublicHold(
  ctx: SweepContext,
  slug: string,
  date: string
): Promise<{ id: string; sessionId: string }> {
  const res = await asAdmin(ctx, {
    method: "POST",
    url: `/public/v1/venues/${slug}/holds`,
    payload: { date, startTime: `${date}T18:00:00Z`, partySize: 2 },
  });
  const { data } = JSON.parse(res.body) as { data: { id: string; sessionId: string } };
  return { id: data.id, sessionId: data.sessionId };
}

/**
 * Creates a disposable reservation (its own fresh table, so repeated calls
 * never collide) directly via the already-proven staff create routes, with a
 * caller-chosen `guestEmail` — the token-route fixtures below mint a manage
 * token against this exact email, so it must be known up front rather than
 * generated by `createDisposableReservation`'s own random one.
 */
async function createDisposableManagedReservation(
  ctx: SweepContext,
  guestEmail: string,
  date: string
): Promise<string> {
  const tableRes = await asAdmin(ctx, {
    method: "POST",
    url: "/api/v1/tables",
    payload: {
      name: `RLS Sweep Item-4 Table ${randomUUID()}`,
      capacity: 4,
      venueId: ctx.venueA.id,
    },
  });
  const { data: table } = JSON.parse(tableRes.body) as { data: { id: string } };

  const res = await asAdmin(ctx, {
    method: "POST",
    url: "/api/v1/reservations",
    payload: {
      date,
      startTime: `${date}T18:00:00Z`,
      endTime: `${date}T20:00:00Z`,
      partySize: 2,
      tableId: table.id,
      venueId: ctx.venueA.id,
      guestName: "RLS Sweep Item-4 Guest",
      guestEmail,
    },
  });
  const { data } = JSON.parse(res.body) as { data: { id: string } };
  return data.id;
}

const publicFunnelFixtures: Record<string, RouteFixture> = {
  "GET /public/v1/venues/:slug": {
    kind: "ok",
    run: async (ctx) => {
      const res = await asAdmin(ctx, {
        method: "GET",
        url: `/public/v1/venues/${ctx.venueA.slug}`,
      });
      expectOk(res, "get public venue config");
      const body = JSON.parse(res.body) as { data: { slug: string } };
      expect(body.data.slug, "must serve the venue matching the slug").toBe(ctx.venueA.slug);

      expectDenied(
        await asAdmin(ctx, { method: "GET", url: `/public/v1/venues/${UNKNOWN_SLUG}` }),
        "unknown slug"
      );
    },
  },
  "GET /public/v1/venues/:slug/availability": {
    kind: "ok",
    run: async (ctx) => {
      expectOk(
        await asAdmin(ctx, {
          method: "GET",
          url: `/public/v1/venues/${ctx.venueA.slug}/availability?date=2026-10-01&partySize=2`,
        }),
        "get availability under the slug-resolved venue"
      );

      expectDenied(
        await asAdmin(ctx, {
          method: "GET",
          url: `/public/v1/venues/${UNKNOWN_SLUG}/availability?date=2026-10-01&partySize=2`,
        }),
        "unknown slug"
      );
    },
  },
  "POST /public/v1/venues/:slug/holds": {
    kind: "ok",
    run: async (ctx) => {
      const res = await asAdmin(ctx, {
        method: "POST",
        url: `/public/v1/venues/${ctx.venueA.slug}/holds`,
        payload: { date: "2026-10-08", startTime: "2026-10-08T18:00:00Z", partySize: 2 },
      });
      expectOk(res, "create hold under the slug-resolved venue");
      const body = JSON.parse(res.body) as { data: { venueId: string } };
      expect(body.data.venueId, "hold must be created under the slug's own venue").toBe(
        ctx.venueA.id
      );

      expectDenied(
        await asAdmin(ctx, {
          method: "POST",
          url: `/public/v1/venues/${UNKNOWN_SLUG}/holds`,
          payload: { date: "2026-10-08", startTime: "2026-10-08T18:00:00Z", partySize: 2 },
        }),
        "unknown slug"
      );
    },
  },
  // `reservation_holds` carries no RLS policy at all (ADR-026 §1) and this
  // route never resolves the venue by slug at all — no `resolveVenueBySlug`
  // call in `public-holds.ts`'s DELETE handler — so it's genuinely not-rls,
  // not item-3, and `holdService.release` is idempotent (always 204,
  // matching/nonexistent holdId alike). Unchanged by #5369 PR 8.
  "DELETE /public/v1/venues/:slug/holds/:holdId": {
    kind: "not-rls",
    run: async (ctx) => {
      expectOk(
        await asAdmin(ctx, {
          method: "DELETE",
          url: `/public/v1/venues/${ctx.venueA.slug}/holds/does-not-exist`,
          headers: { "x-session-id": "rls-sweep-session" },
        }),
        "release hold (public, always-204, not-rls)"
      );
    },
  },
  "GET /public/v1/venues/:slug/holds/:holdId": {
    kind: "ok",
    run: async (ctx) => {
      const hold = await createDisposablePublicHold(ctx, ctx.venueA.slug, "2026-10-12");

      const res = await asAdmin(ctx, {
        method: "GET",
        url: `/public/v1/venues/${ctx.venueA.slug}/holds/${hold.id}`,
        headers: { "x-session-id": hold.sessionId },
      });
      expectOk(res, "read back the hold under its own venue's slug");
      const body = JSON.parse(res.body) as { data: { id: string } };
      expect(body.data.id, "must return the hold matching the id").toBe(hold.id);

      // Same hold, same real session — but addressed through venue B's slug.
      // The hold's own venueId (A) no longer matches the resolved context
      // (B), so it must read as absent, never leak that it exists elsewhere.
      expectDenied(
        await asAdmin(ctx, {
          method: "GET",
          url: `/public/v1/venues/${ctx.venueB.slug}/holds/${hold.id}`,
          headers: { "x-session-id": hold.sessionId },
        }),
        "wrong venue slug"
      );
    },
  },
  "POST /public/v1/venues/:slug/holds/:holdId/confirm": {
    kind: "ok",
    run: async (ctx) => {
      const hold = await createDisposablePublicHold(ctx, ctx.venueA.slug, "2026-10-09");
      expectOk(
        await asAdmin(ctx, {
          method: "POST",
          url: `/public/v1/venues/${ctx.venueA.slug}/holds/${hold.id}/confirm`,
          headers: { "x-session-id": hold.sessionId },
          payload: {
            guestName: "RLS Sweep",
            guestEmail: `rls-sweep-confirm-${randomUUID()}@example.com`,
          },
        }),
        "confirm hold into a reservation under its own venue's slug"
      );

      // A second, never-confirmed hold — addressed through venue B's slug.
      // Its own venueId (A) doesn't match the resolved context, so the
      // confirm attempt must deny rather than silently confirm under B.
      const otherHold = await createDisposablePublicHold(ctx, ctx.venueA.slug, "2026-10-15");
      expectDenied(
        await asAdmin(ctx, {
          method: "POST",
          url: `/public/v1/venues/${ctx.venueB.slug}/holds/${otherHold.id}/confirm`,
          headers: { "x-session-id": otherHold.sessionId },
          payload: { guestName: "RLS Sweep", guestEmail: "rls-sweep-confirm-wrong@example.com" },
        }),
        "wrong venue slug"
      );
    },
  },
  "POST /public/v1/venues/:slug/reservations": {
    kind: "ok",
    run: async (ctx) => {
      const hold = await createDisposablePublicHold(ctx, ctx.venueA.slug, "2026-10-10");
      expectOk(
        await asAdmin(ctx, {
          method: "POST",
          url: `/public/v1/venues/${ctx.venueA.slug}/reservations`,
          headers: { "x-session-id": hold.sessionId },
          payload: {
            holdId: hold.id,
            guestName: "RLS Sweep",
            guestEmail: `rls-sweep-public-res-${randomUUID()}@example.com`,
          },
        }),
        "confirm hold into a reservation via the older public /reservations route"
      );

      expectDenied(
        await asAdmin(ctx, {
          method: "POST",
          url: `/public/v1/venues/${UNKNOWN_SLUG}/reservations`,
          headers: { "x-session-id": "rls-sweep-session" },
          payload: { holdId: "does-not-exist", guestName: "x", guestEmail: "x@example.com" },
        }),
        "unknown slug"
      );
    },
  },
  "GET /public/v1/venues/:slug/guests/recognize": {
    kind: "ok",
    run: async (ctx) => {
      expectOk(
        await asAdmin(ctx, {
          method: "GET",
          url: `/public/v1/venues/${ctx.venueA.slug}/guests/recognize?email=rls-sweep-public@example.com`,
        }),
        "recognize guest under the slug-resolved venue"
      );

      expectDenied(
        await asAdmin(ctx, {
          method: "GET",
          url: `/public/v1/venues/${UNKNOWN_SLUG}/guests/recognize?email=rls-sweep-public@example.com`,
        }),
        "unknown slug"
      );
    },
  },
  "GET /public/v1/venues/:slug/guest-risk": {
    kind: "ok",
    run: async (ctx) => {
      expectOk(
        await asAdmin(ctx, {
          method: "GET",
          url: `/public/v1/venues/${ctx.venueA.slug}/guest-risk?email=rls-sweep-public@example.com`,
        }),
        "guest risk under the slug-resolved venue"
      );

      expectDenied(
        await asAdmin(ctx, {
          method: "GET",
          url: `/public/v1/venues/${UNKNOWN_SLUG}/guest-risk?email=rls-sweep-public@example.com`,
        }),
        "unknown slug"
      );
    },
  },
  // `body.venueId` is REQUIRED by this route's own schema but the handler
  // never reads it for venue resolution ("never the client-supplied
  // body.venueId, which could target another venue" — its own doc comment).
  // Deliberately spoofed to venue B here: the join must still land under
  // venue A (the slug), proving the fix rather than merely tolerating it.
  "POST /public/v1/venues/:slug/waitlist": {
    kind: "ok",
    run: async (ctx) => {
      expectOk(
        await asAdmin(ctx, {
          method: "POST",
          url: `/public/v1/venues/${ctx.venueA.slug}/waitlist`,
          payload: {
            venueId: ctx.venueB.id,
            partySize: 2,
            guestName: "RLS Sweep",
            guestPhone: "+15550002222",
          },
        }),
        "join waitlist under the slug-resolved venue, ignoring a spoofed body.venueId"
      );

      expectDenied(
        await asAdmin(ctx, {
          method: "POST",
          url: `/public/v1/venues/${UNKNOWN_SLUG}/waitlist`,
          payload: {
            venueId: ctx.venueA.id,
            partySize: 2,
            guestName: "RLS Sweep",
            guestPhone: "+15550002222",
          },
        }),
        "unknown slug"
      );
    },
  },
  // venue A has `depositEnabled: false` (seeded with no override) — reaching
  // this 422 business-rule branch, rather than a 500 from the tripwire,
  // proves the venue resolved and the policy lookup ran inside a real RLS
  // context. No live Stripe call is needed to prove that.
  "POST /public/v1/venues/:slug/deposits/payment-intent": {
    kind: "ok",
    run: async (ctx) => {
      const res = await asAdmin(ctx, {
        method: "POST",
        url: `/public/v1/venues/${ctx.venueA.slug}/deposits/payment-intent`,
        payload: { reservationId: ctx.reservationA, guestEmail: "rls-sweep-public@example.com" },
      });
      expect(
        res.statusCode,
        `expected the depositEnabled=false business-rule branch, got ${res.statusCode}: ${res.body}`
      ).toBe(422);

      expectDenied(
        await asAdmin(ctx, {
          method: "POST",
          url: `/public/v1/venues/${UNKNOWN_SLUG}/deposits/payment-intent`,
          payload: { reservationId: "does-not-exist" },
        }),
        "unknown slug"
      );
    },
  },
};

/**
 * Holds (staff confirm route) — a discovery beyond ADR-026 §3.3's own eight
 * items, found while building this sweep. `POST /api/v1/holds` and its
 * plain GET/DELETE siblings are genuinely "not-rls" (see the main fixtures
 * file): `reservation_holds` carries no RLS policy at all. But `.../confirm`
 * (`confirm-hold.ts`) additionally resolves the hold's venue via an
 * unscoped `prisma.venue.findUnique({ where: { id: hold.venueId } })` before
 * creating the resulting reservation — the identical "lookup can't run
 * inside the scope it's computing" shape as items 1-8, just on a table the
 * ADR's own audit never named. Filed here rather than silently rolled into
 * the not-rls bucket precisely because it IS an RLS-table read. Still open —
 * #5369 PR 8 only closes items 3 and 4.
 *
 * `confirmHold`'s session check (Step 2) runs BEFORE the unscoped venue
 * lookup and rejects a mismatched session with `SESSION_MISMATCH` — so this
 * needs the hold's REAL seeded session id, not a placeholder, to actually
 * reach the bug rather than a coincidental 403 one step earlier.
 */
const holdConfirmFixtures: Record<string, RouteFixture> = {
  "POST /api/v1/holds/:id/confirm": brokenPublic(
    "sweep-discovered",
    "POST",
    (ctx) => `/api/v1/holds/${ctx.holdA}/confirm`,
    { guestName: "RLS Sweep", guestEmail: "rls-sweep-confirm@example.com" },
    { headersFor: (ctx) => ({ "x-session-id": ctx.holdSessionId }) }
  ),
};

/**
 * Token-addressed guest surfaces (ADR-026 §3.3 item 4, closed by #5369 PR 8).
 * Each token is generated with the SAME module the route verifies against
 * (`generateManageToken`/`generateUnsubscribeToken`), so a real, validly
 * signed token reaches the handler and the proof is the now-scoped
 * `reservationService.getById`/`guestService.markUnsubscribed` read itself.
 * The mutating routes (`PATCH`/`DELETE manage`, `PATCH confirm`) each use
 * their OWN disposable reservation rather than the shared `ctx.reservationA`
 * — `reservationA` is read by other fixtures across both this file and the
 * staff one, and a cancel/modify here would corrupt state for whichever
 * fixture reads it next. `GET manage` is read-only, so it safely reuses it.
 */
const tokenRouteFixtures: Record<string, RouteFixture> = {
  "GET /public/v1/reservations/manage": {
    kind: "ok",
    run: async (ctx) => {
      const { generateManageToken } = await loadTokenHelpers();
      const token = generateManageToken(ctx.reservationA, ctx.reservationAGuestEmail);
      const res = await asAdmin(ctx, {
        method: "GET",
        url: `/public/v1/reservations/manage?token=${token}`,
      });
      expectOk(res, "read a managed reservation under its resolved venue");
      const body = JSON.parse(res.body) as { data: { reservation: { id: string } } };
      expect(body.data.reservation.id, "must return the reservation the token addresses").toBe(
        ctx.reservationA
      );

      const goneToken = generateManageToken("rls-sweep-no-such-reservation", "nobody@example.com");
      const denied = await asAdmin(ctx, {
        method: "GET",
        url: `/public/v1/reservations/manage?token=${goneToken}`,
      });
      expect(denied.statusCode, `expected 404, got ${denied.statusCode}: ${denied.body}`).toBe(404);
    },
  },
  "PATCH /public/v1/reservations/manage": {
    kind: "ok",
    run: async (ctx) => {
      const { generateManageToken } = await loadTokenHelpers();
      const guestEmail = `rls-sweep-modify-${randomUUID()}@example.com`;
      const reservationId = await createDisposableManagedReservation(ctx, guestEmail, "2026-10-13");
      const token = generateManageToken(reservationId, guestEmail);

      expectOk(
        await asAdmin(ctx, {
          method: "PATCH",
          url: `/public/v1/reservations/manage?token=${token}`,
          payload: { partySize: 3 },
        }),
        "modify a managed reservation under its resolved venue"
      );

      const goneToken = generateManageToken("rls-sweep-no-such-reservation", "nobody@example.com");
      const denied = await asAdmin(ctx, {
        method: "PATCH",
        url: `/public/v1/reservations/manage?token=${goneToken}`,
        payload: { partySize: 3 },
      });
      expect(denied.statusCode, `expected 404, got ${denied.statusCode}: ${denied.body}`).toBe(404);
    },
  },
  "DELETE /public/v1/reservations/manage": {
    kind: "ok",
    run: async (ctx) => {
      const { generateManageToken } = await loadTokenHelpers();
      const guestEmail = `rls-sweep-cancel-${randomUUID()}@example.com`;
      const reservationId = await createDisposableManagedReservation(ctx, guestEmail, "2026-10-16");
      const token = generateManageToken(reservationId, guestEmail);

      expectOk(
        await asAdmin(ctx, {
          method: "DELETE",
          url: `/public/v1/reservations/manage?token=${token}`,
        }),
        "cancel a managed reservation under its resolved venue"
      );

      const goneToken = generateManageToken("rls-sweep-no-such-reservation", "nobody@example.com");
      const denied = await asAdmin(ctx, {
        method: "DELETE",
        url: `/public/v1/reservations/manage?token=${goneToken}`,
      });
      expect(denied.statusCode, `expected 404, got ${denied.statusCode}: ${denied.body}`).toBe(404);
    },
  },
  "PATCH /public/v1/reservations/confirm": {
    kind: "ok",
    run: async (ctx) => {
      const { generateManageToken } = await loadTokenHelpers();
      const guestEmail = `rls-sweep-confirm-attendance-${randomUUID()}@example.com`;
      const reservationId = await createDisposableManagedReservation(ctx, guestEmail, "2026-10-17");
      const token = generateManageToken(reservationId, guestEmail);

      expectOk(
        await asAdmin(ctx, {
          method: "PATCH",
          url: `/public/v1/reservations/confirm?token=${token}`,
        }),
        "confirm attendance under the resolved venue"
      );

      // A NULL resolution here answers 401 (invalid-link HTML), same as an
      // unverifiable token — see confirm-attendance.ts's own doc comment.
      const goneToken = generateManageToken("rls-sweep-no-such-reservation", "nobody@example.com");
      const denied = await asAdmin(ctx, {
        method: "PATCH",
        url: `/public/v1/reservations/confirm?token=${goneToken}`,
      });
      expect(denied.statusCode, `expected 401, got ${denied.statusCode}`).toBe(401);
    },
  },
  "GET /public/v1/guests/unsubscribe": {
    kind: "ok",
    run: async (ctx) => {
      const { generateUnsubscribeToken } = await loadTokenHelpers();
      const token = generateUnsubscribeToken(ctx.guestA);
      expectOk(
        await asAdmin(ctx, { method: "GET", url: `/public/v1/guests/unsubscribe?token=${token}` }),
        "unsubscribe under the resolved venue"
      );

      const goneToken = generateUnsubscribeToken("rls-sweep-no-such-guest");
      const denied = await asAdmin(ctx, {
        method: "GET",
        url: `/public/v1/guests/unsubscribe?token=${goneToken}`,
      });
      expect(denied.statusCode, `expected 404, got ${denied.statusCode}: ${denied.body}`).toBe(404);
      expect(
        (JSON.parse(denied.body) as { code?: string }).code,
        "must carry the GUEST_NOT_FOUND extension"
      ).toBe("GUEST_NOT_FOUND");
    },
  },
};

/**
 * The Stripe webhook (item 4's other half, closed by #5369 PR 8):
 * `onPaymentIntentSucceeded` calls `depositService.getByPaymentIntentId`,
 * now resolved through `withDepositVenueContext` before it can transition
 * the deposit. Signed with the real `stripe` SDK's own test-signature helper
 * against the SAME `STRIPE_WEBHOOK_SECRET` the app was booted with, so
 * signature verification passes and the proof is the now-scoped deposit
 * read behind it.
 */
const stripeWebhookFixtures: Record<string, RouteFixture> = {
  "POST /api/v1/stripe/webhook": {
    kind: "ok",
    run: async (ctx) => {
      const rawSecret = process.env.STRIPE_WEBHOOK_SECRET;
      if (!rawSecret) throw new Error("STRIPE_WEBHOOK_SECRET must be set before this fixture runs");
      const secret: string = rawSecret;

      async function sendPaymentIntentSucceeded(paymentIntentId: string) {
        const event = {
          id: `evt_rls_sweep_${randomUUID()}`,
          object: "event",
          type: "payment_intent.succeeded",
          data: { object: { id: paymentIntentId, object: "payment_intent" } },
        };
        const payload = JSON.stringify(event);
        const signature = await Stripe.webhooks.generateTestHeaderStringAsync({ payload, secret });

        // Bypasses the shared `inject()` helper (raw body needed for the
        // signature, and no `x-auth-bypass` gate applies to a webhook) —
        // reset the tripwire tracker by hand, same contract `inject()`
        // gives every other fixture.
        ctx.lastRlsErrorName = null;
        return ctx.app.inject({
          method: "POST",
          url: "/api/v1/stripe/webhook",
          headers: {
            ...ADMIN_HEADERS,
            "stripe-signature": signature,
            "content-type": "application/json",
          },
          payload,
        });
      }

      expectOk(
        await sendPaymentIntentSucceeded(ctx.depositWithPiAPaymentIntentId),
        "stripe webhook payment_intent.succeeded (venue resolved)"
      );

      // Read the deposit back the SAME way the app itself would — the
      // wrapped `prisma` export inside a real venue context, never a raw
      // client — matching this suite's own non-HTTP job-handler checks.
      const { prisma } = await import("../services/database.js");
      const { runWithVenueContext } = await import("../services/venue-context-store.js");
      const deposit = await runWithVenueContext(ctx.venueA.id, () =>
        prisma.deposit.findUnique({ where: { id: ctx.depositWithPiA } })
      );
      expect(deposit?.status, "webhook must transition the deposit pending -> held").toBe("held");

      // A PaymentIntent id no deposit carries at all: resolveVenueId returns
      // NULL, and withDepositVenueContext's no-op contract means the handler
      // body never runs — not a 500 retry loop.
      expectOk(
        await sendPaymentIntentSucceeded("pi_rls_sweep_does_not_exist"),
        "unknown PaymentIntent id — no-op, not a 500 retry loop"
      );
    },
  },
};

export const PUBLIC_FIXTURES: Record<string, RouteFixture> = {
  ...publicFunnelFixtures,
  ...holdConfirmFixtures,
  ...tokenRouteFixtures,
  ...stripeWebhookFixtures,
};
