export enum JobType {
  BOOKING_REMINDER = "BOOKING_REMINDER",
  DAY_OF_REMINDER = "DAY_OF_REMINDER",
  POST_VISIT_FOLLOWUP = "POST_VISIT_FOLLOWUP",
  PRE_ARRIVAL_BRIEFING = "PRE_ARRIVAL_BRIEFING",
  LAPSED_GUEST_SCAN = "LAPSED_GUEST_SCAN",
  WAITLIST_EXPIRY = "WAITLIST_EXPIRY",
}
