/**
 * Sample data for the Visual Test Harness.
 *
 * Extracted from VisualTest.tsx — values are unchanged, only relocated.
 */

export const selectOptions = [
  { value: "apple", label: "Apple" },
  { value: "banana", label: "Banana" },
  { value: "cherry", label: "Cherry" },
];

export const tableColumns = [
  { key: "name" as const, header: "Name", sortable: true },
  { key: "role" as const, header: "Role" },
  { key: "status" as const, header: "Status" },
];

export const tableData = [
  { id: "1", name: "Alice", role: "Engineer", status: "Active" },
  { id: "2", name: "Bob", role: "Designer", status: "Away" },
  { id: "3", name: "Carol", role: "Manager", status: "Active" },
];

export const tapeChartDefaultRooms = [
  { id: "r1", name: "101", category: "Standard", capacity: 2, status: "ready" as const },
  { id: "r2", name: "102", category: "Standard", capacity: 2, status: "occupied" as const },
  { id: "r3", name: "103", category: "Standard", capacity: 2, status: "dirty" as const },
  { id: "r4", name: "104", category: "Deluxe", capacity: 3, status: "ready" as const },
  { id: "r5", name: "105", category: "Deluxe", capacity: 3, status: "occupied" as const },
  { id: "r6", name: "106", category: "Deluxe", capacity: 3, status: "outOfOrder" as const },
  { id: "r7", name: "107", category: "Suite", capacity: 4, status: "ready" as const },
  { id: "r8", name: "108", category: "Suite", capacity: 4, status: "occupied" as const },
];

export const tapeChartDefaultReservations = [
  {
    id: "rsv-1",
    roomId: "r1",
    start: "2026-01-15",
    end: "2026-01-18",
    status: "confirmed" as const,
    guestName: "Alice Tanaka",
    ratePerNight: 180,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "rsv-2",
    roomId: "r2",
    start: "2026-01-16",
    end: "2026-01-21",
    status: "checkedIn" as const,
    guestName: "Bob García",
    ratePerNight: 180,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "rsv-3",
    roomId: "r3",
    start: "2026-01-17",
    end: "2026-01-19",
    status: "tentative" as const,
    guestName: "Clara Singh",
    ratePerNight: 180,
    currency: "USD",
    source: "Booking.com",
  },
  {
    id: "rsv-4",
    roomId: "r4",
    start: "2026-01-15",
    end: "2026-01-22",
    status: "checkedIn" as const,
    guestName: "Daniil Patel",
    ratePerNight: 220,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "rsv-5",
    roomId: "r5",
    start: "2026-01-18",
    end: "2026-01-20",
    status: "confirmed" as const,
    guestName: "Erika Mohan",
    ratePerNight: 220,
    currency: "USD",
    source: "Expedia",
  },
  {
    id: "rsv-6",
    roomId: "r7",
    start: "2026-01-15",
    end: "2026-01-17",
    status: "checkedOut" as const,
    guestName: "Fatima Hernández",
    ratePerNight: 320,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "rsv-7",
    roomId: "r7",
    start: "2026-01-19",
    end: "2026-01-22",
    status: "confirmed" as const,
    guestName: "Gabriel Rossi",
    ratePerNight: 320,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "rsv-8",
    roomId: "r8",
    start: "2026-01-16",
    end: "2026-01-19",
    status: "checkedIn" as const,
    guestName: "Hideo Bauer",
    ratePerNight: 320,
    currency: "USD",
    source: "Booking.com",
  },
];

export const tapeChartStressRooms = Array.from({ length: 24 }, (_, i) => {
  const number = 1000 + i;
  const tier = i < 12 ? "Standard" : i < 20 ? "Deluxe" : "Suite";
  const capacity = tier === "Standard" ? 2 : tier === "Deluxe" ? 3 : 4;
  const statuses = ["ready", "occupied", "dirty", "outOfOrder"] as const;
  const status = statuses[i % 4]!;
  return { id: `room-${number}`, name: String(number), category: tier, capacity, status };
});

export const tapeChartStressReservations = [
  {
    id: "s-1",
    roomId: "room-1000",
    start: "2026-01-15",
    end: "2026-01-18",
    status: "confirmed" as const,
    guestName: "Alice Tanaka",
    ratePerNight: 180,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "s-2",
    roomId: "room-1001",
    start: "2026-01-16",
    end: "2026-01-22",
    status: "checkedIn" as const,
    guestName: "Bob García",
    ratePerNight: 180,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "s-3",
    roomId: "room-1002",
    start: "2026-01-17",
    end: "2026-01-19",
    status: "tentative" as const,
    guestName: "Clara Singh",
    ratePerNight: 180,
    currency: "USD",
    source: "Booking.com",
  },
  {
    id: "s-4",
    roomId: "room-1003",
    start: "2026-01-15",
    end: "2026-01-29",
    status: "checkedIn" as const,
    guestName: "Daniil Patel",
    ratePerNight: 180,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "s-5",
    roomId: "room-1004",
    start: "2026-01-18",
    end: "2026-01-21",
    status: "confirmed" as const,
    guestName: "Erika Mohan",
    ratePerNight: 180,
    currency: "USD",
    source: "Expedia",
  },
  {
    id: "s-6",
    roomId: "room-1005",
    start: "2026-01-15",
    end: "2026-01-17",
    status: "checkedOut" as const,
    guestName: "Fatima Hernández",
    ratePerNight: 180,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "s-7",
    roomId: "room-1006",
    start: "2026-01-19",
    end: "2026-01-25",
    status: "confirmed" as const,
    guestName: "Gabriel Rossi",
    ratePerNight: 180,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "s-8",
    roomId: "room-1007",
    start: "2026-01-16",
    end: "2026-01-19",
    status: "checkedIn" as const,
    guestName: "Hideo Bauer",
    ratePerNight: 180,
    currency: "USD",
    source: "Booking.com",
  },
  {
    id: "s-9",
    roomId: "room-1008",
    start: "2026-01-22",
    end: "2026-01-26",
    status: "confirmed" as const,
    guestName: "Ingrid García",
    ratePerNight: 180,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "s-10",
    roomId: "room-1009",
    start: "2026-01-15",
    end: "2026-01-21",
    status: "checkedIn" as const,
    guestName: "Jiro Suzuki",
    ratePerNight: 180,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "s-11",
    roomId: "room-1010",
    start: "2026-01-20",
    end: "2026-01-24",
    status: "confirmed" as const,
    guestName: "Kenji Tanaka",
    ratePerNight: 180,
    currency: "USD",
    source: "Expedia",
  },
  {
    id: "s-12",
    roomId: "room-1011",
    start: "2026-01-17",
    end: "2026-01-23",
    status: "checkedIn" as const,
    guestName: "Liam O'Neill",
    ratePerNight: 180,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "s-13",
    roomId: "room-1012",
    start: "2026-01-15",
    end: "2026-01-19",
    status: "checkedOut" as const,
    guestName: "Mateo Lannister",
    ratePerNight: 220,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "s-14",
    roomId: "room-1013",
    start: "2026-01-21",
    end: "2026-01-26",
    status: "confirmed" as const,
    guestName: "Noa Chen",
    ratePerNight: 220,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "s-15",
    roomId: "room-1014",
    start: "2026-01-16",
    end: "2026-01-20",
    status: "checkedIn" as const,
    guestName: "Oksana Patel",
    ratePerNight: 220,
    currency: "USD",
    source: "Booking.com",
  },
  {
    id: "s-16",
    roomId: "room-1015",
    start: "2026-01-18",
    end: "2026-01-25",
    status: "confirmed" as const,
    guestName: "Priya Singh",
    ratePerNight: 220,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "s-17",
    roomId: "room-1016",
    start: "2026-01-22",
    end: "2026-01-29",
    status: "tentative" as const,
    guestName: "Quinn O'Neill",
    ratePerNight: 220,
    currency: "USD",
    source: "Expedia",
  },
  {
    id: "s-18",
    roomId: "room-1017",
    start: "2026-01-15",
    end: "2026-01-22",
    status: "checkedIn" as const,
    guestName: "Rafael Hernández",
    ratePerNight: 220,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "s-19",
    roomId: "room-1018",
    start: "2026-01-19",
    end: "2026-01-23",
    status: "confirmed" as const,
    guestName: "Sofía Rossi",
    ratePerNight: 220,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "s-20",
    roomId: "room-1019",
    start: "2026-01-17",
    end: "2026-01-21",
    status: "checkedIn" as const,
    guestName: "Tyrion Bauer",
    ratePerNight: 220,
    currency: "USD",
    source: "Booking.com",
  },
  {
    id: "s-21",
    roomId: "room-1020",
    start: "2026-01-15",
    end: "2026-01-29",
    status: "checkedIn" as const,
    guestName: "Ursula Mohan",
    ratePerNight: 320,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "s-22",
    roomId: "room-1021",
    start: "2026-01-20",
    end: "2026-01-25",
    status: "confirmed" as const,
    guestName: "Viktor Suzuki",
    ratePerNight: 320,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "s-23",
    roomId: "room-1022",
    start: "2026-01-16",
    end: "2026-01-22",
    status: "checkedIn" as const,
    guestName: "Wren Tanaka",
    ratePerNight: 320,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "s-24",
    roomId: "room-1023",
    start: "2026-01-23",
    end: "2026-01-28",
    status: "confirmed" as const,
    guestName: "Xander Patel",
    ratePerNight: 320,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "s-25",
    roomId: "room-1003",
    start: "2026-01-19",
    end: "2026-01-21",
    status: "tentative" as const,
    guestName: "Yuki Singh",
    ratePerNight: 180,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "s-26",
    roomId: "room-1009",
    start: "2026-01-23",
    end: "2026-01-26",
    status: "confirmed" as const,
    guestName: "Zara Bauer",
    ratePerNight: 180,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "s-27",
    roomId: "room-1015",
    start: "2026-01-26",
    end: "2026-01-29",
    status: "confirmed" as const,
    guestName: "Anika García",
    ratePerNight: 220,
    currency: "USD",
    source: "Expedia",
  },
  {
    id: "s-28",
    roomId: "room-1017",
    start: "2026-01-25",
    end: "2026-01-28",
    status: "tentative" as const,
    guestName: "Bri Hernández",
    ratePerNight: 220,
    currency: "USD",
    source: "Direct",
  },
  {
    id: "s-29",
    roomId: "room-1023",
    start: "2026-01-15",
    end: "2026-01-19",
    status: "checkedOut" as const,
    guestName: "Cyrus O'Neill",
    ratePerNight: 320,
    currency: "USD",
    source: "Direct",
  },
];
