// AUTO-GENERATED -- do not edit. Run: pnpm --filter @mbe/rialto-catalog generate
import { z } from "zod";

export const generatedSchemas = {
  Accordion: z.object({
    items: z.array(z.object({ id: z.string(), title: z.string(), content: z.string(), disabled: z.boolean().optional() })),
    multiple: z.boolean().optional(),
    headingLevel: z.enum(["h2", "h3", "h4", "h5", "h6"]).optional(),
  }),
  Alert: z.object({
    variant: z.enum(["error", "info", "success", "warning"]).optional(),
    title: z.string().max(60).optional(),
    dismissible: z.boolean().optional(),
    actions: z.string().optional(),
  }),
  AppBar: z.object({
    logo: z.string().optional(),
    actions: z.string().optional(),
    glass: z.boolean().optional(),
    height: z.string().max(20).optional(),
  }),
  AspectRatio: z.object({
    ratio: z.number().optional(),
  }),
  Avatar: z.object({
    src: z.string().optional(),
    alt: z.string().optional(),
    name: z.string().max(30).optional(),
    size: z.enum(["lg", "md", "sm", "xl"]).optional(),
    status: z.enum(["away", "busy", "offline", "online"]).optional(),
    transition: z.enum(["fade", "splitflap"]).optional(),
  }),
  Badge: z.object({
    variant: z.enum(["accent", "error", "neutral", "success", "warning"]).optional(),
    size: z.enum(["md", "sm"]).optional(),
    dot: z.boolean().optional(),
  }),
  Banner: z.object({
    variant: z.enum(["accent", "error", "info", "warning"]).optional(),
    dismissible: z.boolean().optional(),
    action: z.string().optional(),
  }),
  Breadcrumb: z.object({
    items: z.array(z.object({ label: z.string(), href: z.string().optional(), icon: z.string().optional() })),
    maxItems: z.number().optional(),
    separator: z.string().optional(),
  }),
  Button: z.object({
    variant: z.enum(["ghost", "primary", "secondary"]).optional(),
    size: z.enum(["lg", "md", "sm"]).optional(),
    isLoading: z.boolean().optional(),
    loadingText: z.string().optional(),
  }),
  Calendar: z.object({
    min: z.string().optional(),
    max: z.string().optional(),
    locale: z.string().optional(),
  }),
  Card: z.object({
    variant: z.enum(["elevated", "flat", "glass"]).optional(),
    tilt: z.boolean().optional(),
    title: z.string().max(60).optional(),
    subtitle: z.string().max(80).optional(),
  }),
  Checkbox: z.object({
    label: z.string().max(30).optional(),
    checked: z.boolean().optional(),
    defaultChecked: z.boolean().optional(),
    required: z.boolean().optional(),
    indeterminate: z.boolean().optional(),
    disabled: z.boolean().optional(),
    disabledReason: z.string().optional(),
    description: z.string().max(80).optional(),
  }),
  Combobox: z.object({
    options: z.array(z.object({ value: z.string(), label: z.string(), disabled: z.boolean().optional() })),
    label: z.string().max(40).optional(),
    hint: z.string().optional(),
    error: z.boolean().optional(),
    required: z.boolean().optional(),
    showOptional: z.boolean().optional(),
    placeholder: z.string().optional(),
    disabled: z.boolean().optional(),
    multiple: z.boolean().optional(),
    value: z.string().optional(),
    inputValue: z.string().optional(),
    filter: z.boolean().optional(),
    loading: z.boolean().optional(),
    loadingText: z.string().optional(),
    emptyText: z.string().optional(),
  }),
  DataList: z.object({
    items: z.array(z.object({ label: z.string(), value: z.string() })),
    orientation: z.enum(["horizontal", "vertical"]).optional(),
    striped: z.boolean().optional(),
  }),
  DataTable: z.object({
    columns: z.array(z.object({ key: z.string(), header: z.string(), sortable: z.boolean().optional(), align: z.enum(["left", "center", "right"]).optional(), width: z.string().optional(), rowHeader: z.boolean().optional() })),
    data: z.array(z.record(z.string(), z.unknown())),
    density: z.enum(["compact", "default", "spacious"]).optional(),
    striped: z.boolean().optional(),
    emptyMessage: z.string().max(60).optional(),
    label: z.string().optional(),
    selectionMode: z.enum(["multiple", "single"]).optional(),
  }),
  DatePicker: z.object({
    min: z.string().optional(),
    max: z.string().optional(),
    locale: z.string().optional(),
    label: z.string().optional(),
    placeholder: z.string().optional(),
    placement: z.enum(["bottom", "left", "right", "top"]).optional(),
  }),
  DateRange: z.object({
    min: z.string().optional(),
    max: z.string().optional(),
    locale: z.string().optional(),
  }),
  DepartureBoard: z.object({
    phrases: z.array(z.string()),
    holdMs: z.number().optional(),
    flipInterval: z.number().optional(),
    cascadeDelay: z.number().optional(),
    charset: z.enum(["alpha", "alphanumeric", "full", "numeric"]).optional(),
    size: z.enum(["lg", "md", "sm"]).optional(),
    length: z.number().optional(),
  }),
  Dialog: z.object({
    open: z.boolean(),
    title: z.string().max(60).optional(),
    description: z.string().max(120).optional(),
    footer: z.string().optional(),
  }),
  Divider: z.object({
    orientation: z.enum(["horizontal", "vertical"]).optional(),
    label: z.string().max(20).optional(),
    accent: z.boolean().optional(),
    spacing: z.enum(["compact", "default", "spacious"]).optional(),
  }),
  EmptyState: z.object({
    icon: z.string().optional(),
    heading: z.string().max(50).optional(),
    description: z.string().max(300).optional(),
    action: z.string().optional(),
    variant: z.enum(["elevated", "flat"]).optional(),
    size: z.enum(["md", "sm"]).optional(),
  }),
  Footer: z.object({
    variant: z.enum(["minimal", "rich"]).optional(),
    logo: z.string().optional(),
    copyright: z.string().max(80).optional(),
  }),
  Form: z.object({
    showErrorSummary: z.boolean().optional(),
  }),
  FormField: z.object({
    name: z.string(),
  }),
  IconButton: z.object({
    icon: z.string().optional(),
    "aria-label": z.string(),
    size: z.enum(["lg", "md", "sm"]).optional(),
    variant: z.enum(["ghost", "primary", "secondary"]).optional(),
  }),
  Input: z.object({
    label: z.string().max(40).optional(),
    hint: z.string().max(80).optional(),
    error: z.boolean().optional(),
    disabledReason: z.string().optional(),
    startIcon: z.string().optional(),
    endIcon: z.string().optional(),
    showOptional: z.boolean().optional(),
  }),
  NavigationMenu: z.object({
    items: z.array(z.object({ label: z.string(), href: z.string().optional(), children: z.array(z.object({ label: z.string(), href: z.string().optional() })).optional() })),
  }),
  Odometer: z.object({
    value: z.number(),
    size: z.enum(["lg", "md", "sm"]).optional(),
    flipInterval: z.number().optional(),
    cascadeDelay: z.number().optional(),
  }),
  Select: z.object({
    options: z.array(z.object({ value: z.string(), label: z.string(), disabled: z.boolean().optional() })),
    value: z.string().optional(),
    placeholder: z.string().optional(),
    label: z.string().max(40).optional(),
    hint: z.string().optional(),
    error: z.boolean().optional(),
    required: z.boolean().optional(),
    showOptional: z.boolean().optional(),
    disabled: z.boolean().optional(),
    disabledReason: z.string().optional(),
    "aria-label": z.string().optional(),
    "aria-labelledby": z.string().optional(),
  }),
  Sidebar: z.object({
    items: z.array(z.union([z.object({ id: z.string(), label: z.string(), icon: z.string().optional(), href: z.string().optional(), active: z.boolean().optional(), disabled: z.boolean().optional() }), z.object({ label: z.string().optional(), items: z.array(z.object({ id: z.string(), label: z.string(), icon: z.string().optional(), href: z.string().optional(), active: z.boolean().optional(), disabled: z.boolean().optional() })) })])),
    collapsed: z.boolean().optional(),
  }),
  Stack: z.object({
    direction: z.enum(["column", "row"]).optional(),
    gap: z.enum(["2xl", "2xs", "3xl", "lg", "md", "sm", "xl", "xs"]).optional(),
    align: z.enum(["baseline", "center", "end", "start", "stretch"]).optional(),
    justify: z.enum(["between", "center", "end", "start"]).optional(),
    wrap: z.boolean().optional(),
  }),
  Table: z.object({
    columns: z.array(z.object({ key: z.string(), header: z.string(), sortable: z.boolean().optional(), align: z.enum(["left", "center", "right"]).optional(), width: z.string().optional() })),
    data: z.array(z.record(z.string(), z.unknown())),
    density: z.enum(["compact", "default", "spacious"]).optional(),
    striped: z.boolean().optional(),
    emptyMessage: z.string().max(60).optional(),
  }),
  Tabs: z.object({
    tabs: z.array(z.object({ id: z.string(), label: z.string(), disabled: z.boolean().optional(), content: z.string() })),
    defaultTab: z.string().optional(),
  }),
  Text: z.object({
    variant: z.enum(["body", "caption", "detail", "display", "label"]).optional(),
    color: z.enum(["accent", "error", "on-accent", "primary", "secondary", "success", "tertiary", "warning"]).optional(),
    align: z.enum(["center", "left", "right"]).optional(),
    mono: z.boolean().optional(),
    truncate: z.boolean().optional(),
  }),
  TimePicker: z.object({
    step: z.number().optional(),
    min: z.string().optional(),
    max: z.string().optional(),
    locale: z.string().optional(),
    label: z.string().optional(),
    placeholder: z.string().optional(),
    placement: z.enum(["bottom", "left", "right", "top"]).optional(),
  }),
  Toast: z.object({
    title: z.string().max(50),
    description: z.string().max(120).optional(),
    variant: z.enum(["default", "success", "error", "accent"]).optional(),
    duration: z.number().optional(),
  }),
  Toggle: z.object({
    label: z.string().max(30).optional(),
    checked: z.boolean().optional(),
    disabledReason: z.string().optional(),
  }),
} as const;
